# Generated by Django 4.0.5 on 2022-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readnews', '0002_new_date_new_speech_new_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
